### ISSUE TITLE
Is it possible to update the react version?

### ISSUE THREAD

**Issue by dirkesquire** [wsmd/use-clipboard-copy#17]
Getting this warning:

warning " > use-clipboard-copy@0.1.2" has incorrect peer dependency "react@^16.8.0".

We are using: "react": "^17.0.1"

**Comment by dennismorello** [comment]
It has been fixed by #14.

**Comment by dirkesquire** [comment]
Perfect! Thanks!

**Comment by wsmd** [comment]
Just pushed a new release to npm with the updated peer dependency version. The warning should go disappear once you update to `use-clipboard-copy@0.2.0`.

**Comment by dirkesquire** [comment]
Great, yes the warning has gone away. Thanks again!
